version: '3.10.11'
services:
  web:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - /home/ubuntu/working/media:/home/ubuntu/working/media
    env_file:
      - .env
    container_name: eight-cross-eight
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_USER}
    ports:
      - "5432:5432"


volumes:
  postgres_data:
